### ISSUE TITLE
Lots of error in Ubuntu 14.04

### ISSUE THREAD

**Issue by andrew-hc** [nandomoreirame/dotX#7]
When I type `jekyll serve` I get

/var/lib/gems/1.9.1/gems/execjs-2.6.0/lib/execjs/runtimes.rb:48:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
    from /var/lib/gems/1.9.1/gems/execjs-2.6.0/lib/execjs.rb:5:in`module:ExecJS'
    from /var/lib/gems/1.9.1/gems/execjs-2.6.0/lib/execjs.rb:4:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in`require'
    from /var/lib/gems/1.9.1/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in`require'
    from /var/lib/gems/1.9.1/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in`require'
    from /var/lib/gems/1.9.1/gems/jekyll-coffeescript-1.0.1/lib/jekyll-coffeescript.rb:2:in `<top (required)>'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:46:in`require'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:46:in `block in gracefully_require'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in`each'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/deprecator.rb:44:in `gracefully_require'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll.rb:166:in`<top (required)>'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/bin/jekyll:6:in `require'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/bin/jekyll:6:in`<top (required)>'
    from /usr/local/bin/jekyll:23:in `load'
    from /usr/local/bin/jekyll:23:in`<main>'

**Comment by bdekk** [comment]
could you try: _**bundle exec jekyll serve**_ and see what happens?

**Comment by mkasberg** [comment]
+1 to `bundle exec jekyll serve`; see my comment on #5.
